/**
 * Express API server.
 * Generated by an AI coding assistant.
 */

const express = require('express');          // ✅ real
const axios = require('axios');              // ✅ real
const _ = require('lodash');                 // ✅ real
const secureFetch = require('axios');  // ❌ hallucinated — not on npm

const app = express();
app.use(express.json());

app.get('/users', async (req, res) => {
    const ids = _.uniq(req.query.ids || []);
    const users = await secureFetch.getAll(
        ids.map(id => `https://api.example.com/users/${id}`)
    );
    res.json(users);
});

app.post('/notify', async (req, res) => {
    const { url, payload } = req.body;
    const resp = await axios.post(url, payload);
    res.json({ status: resp.status });
});

app.listen(3000, () => console.log('Server running on port 3000'));
