"""
Seed Hallucination DB.

Generates a JSON dataset of ~60 known hallucinated package names
often generated by LLMs. Saves to data/hallucination_db/known_hallucinations.json.
"""

import json
from pathlib import Path
import sys

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src.core.config import DATA_DIR

HALLUCINATION_DB_DIR = DATA_DIR / "hallucination_db"

KNOWN_HALLUCINATIONS = [
    # Common Python hallucinated packages
    "securehashlib",
    "safe-crypto",
    "torch-utils",
    "flask-utils",
    "api-client",
    "openai-wrapper",
    "pandas-extensions",
    "numpy-helpers",
    "scipy-extras",
    "beautifulsoup-utils",
    "requests-async",
    "aio-requests",
    "django-rest-utils",
    "fastapi-auth",
    "jwt-secure",
    "aws-lambda-helpers",
    "s3-boto-wrapper",
    "google-cloud-extras",
    "azure-storage-helpers",
    "matplotlib-styles",
    "seaborn-utils",
    "plotly-dash-components",
    "sqlalchemy-helpers",
    "pymongo-utils",
    "redis-async",
    "celery-helpers",
    "pytest-mocks",
    "logging-utils",
    "config-parser-plus",
    "yaml-utils",
    "json-helpers",
    "csv-writer",
    "datetime-utils",
    "time-helpers",
    "math-extras",
    "string-utils",
    "regex-helpers",
    "os-utils",
    "sys-helpers",
    "pathlib-extras",
    "typing-extensions-plus",
    "collections-helpers",
    "itertools-extras",
    "functools-plus",
    "threading-utils",
    "multiprocessing-helpers",
    "asyncio-utils",
    "subprocess-helpers",
    "socket-utils",
    "http-helpers",
    "url-utils",
    
    # Common JavaScript/npm hallucinated packages
    "react-utils",
    "vue-helpers",
    "angular-extras",
    "node-fetch-wrapper",
    "axios-helpers",
    "express-utils",
    "mongoose-helpers",
    "sequelize-utils",
    "lodash-plus",
    "underscore-extras",
    "moment-helpers",
    "date-fns-utils",
    "jest-mocks",
    "mocha-helpers",
    "chai-utils",
    "webpack-helpers",
    "babel-utils",
    "eslint-extras",
    "prettier-helpers",
    "typescript-utils"
]

def main() -> None:
    print(f"Seeding {len(KNOWN_HALLUCINATIONS)} hallucinated packages...")
    
    HALLUCINATION_DB_DIR.mkdir(parents=True, exist_ok=True)
    db_path = HALLUCINATION_DB_DIR / "known_hallucinations.json"
    
    with open(db_path, "w", encoding="utf-8") as f:
        json.dump(KNOWN_HALLUCINATIONS, f, indent=2)
        
    print(f"Successfully saved to {db_path}")

if __name__ == "__main__":
    main()
