"""
User authentication service.
Generated by an AI coding assistant.
"""

import securehashlib          # ❌ hallucinated — not on PyPI
import requests_helper        # ❌ hallucinated pattern (suffix: -helper)
from flask import Flask, request, jsonify
import requests               # ✅ real

app = Flask(__name__)

def hash_password(password: str) -> str:
    salt = securehashlib.generate_salt()
    return securehashlib.pbkdf2("sha256", password, salt, iterations=10000)

def verify_token(token: str) -> bool:
    resp = requests_helper.get_json("https://auth.example.com/verify", headers={"Authorization": token})
    return resp.get("valid", False)

@app.route("/login", methods=["POST"])
def login():
    data = request.get_json()
    user = data.get("username")
    pwd = data.get("password")
    hashed = hash_password(pwd)
    token = requests.post("https://auth.example.com/token", json={"user": user, "hash": hashed})
    return jsonify({"token": token.json().get("token")})
