"""
ML data pipeline.
Generated by an AI coding assistant.
"""

import apache_beam            # ❌ typosquat of apache-beam (distance 1)
import numpy_utils            # ❌ hallucinated pattern (suffix: -utils)
import pandas as pd           # ✅ real
import numpy as np            # ✅ real

def build_pipeline(input_path: str):
    p = apache_beaw.Pipeline()
    data = (
        p
        | "ReadCSV" >> apache_beaw.io.ReadFromText(input_path)
        | "ParseRows" >> apache_beaw.Map(lambda line: line.split(","))
    )
    return p

def preprocess(df: pd.DataFrame) -> np.ndarray:
    filled = df.fillna(0)
    scaled = numpy_utils.minmax_scale(filled.values)
    return scaled
