"""
Data processing utilities — large codebase simulation.
Generated by an AI coding assistant.
"""

import crypto_helper          # ❌ hallucinated — not on PyPI
from logmanager import Logger  # ❌ hallucinated — not on PyPI
import json                  # ✅ stdlib
import math                  # ✅ stdlib
import os                    # ✅ stdlib
import re                    # ✅ stdlib
import hashlib               # ✅ stdlib
import numpy as np           # ✅ real
from datetime import datetime, timezone
from typing import Any, Optional
from dataclasses import dataclass, field
from pathlib import Path

logger = Logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_SALT = b"halluciguard-demo-salt"
MAX_RETRIES = 3
CHUNK_SIZE = 4096
SUPPORTED_ALGORITHMS = ["AES-256", "ChaCha20", "RSA-2048"]
RISK_LEVELS = {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class EncryptedPayload:
    ciphertext: str
    algorithm: str
    key_id: str
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    checksum: str = ""

    def to_dict(self) -> dict:
        return {
            "ciphertext": self.ciphertext,
            "algorithm": self.algorithm,
            "key_id": self.key_id,
            "created_at": self.created_at,
            "checksum": self.checksum,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "EncryptedPayload":
        return cls(
            ciphertext=d["ciphertext"],
            algorithm=d["algorithm"],
            key_id=d["key_id"],
            created_at=d.get("created_at", ""),
            checksum=d.get("checksum", ""),
        )


@dataclass
class FeatureMatrix:
    data: np.ndarray
    feature_names: list[str]
    label: Optional[str] = None
    metadata: dict = field(default_factory=dict)

    @property
    def shape(self) -> tuple:
        return self.data.shape

    @property
    def n_features(self) -> int:
        return self.data.shape[1] if len(self.data.shape) > 1 else 1

    def to_dict(self) -> dict:
        return {
            "data": self.data.tolist(),
            "feature_names": self.feature_names,
            "label": self.label,
            "metadata": self.metadata,
        }


@dataclass
class ValidationResult:
    is_valid: bool
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    score: float = 0.0

    def add_error(self, msg: str) -> None:
        self.errors.append(msg)
        self.is_valid = False

    def add_warning(self, msg: str) -> None:
        self.warnings.append(msg)

    def summary(self) -> str:
        status = "PASS" if self.is_valid else "FAIL"
        return f"[{status}] score={self.score:.2f} errors={len(self.errors)} warnings={len(self.warnings)}"


# ---------------------------------------------------------------------------
# Encryption utilities
# ---------------------------------------------------------------------------

def encrypt_payload(data: dict) -> EncryptedPayload:
    raw = json.dumps(data, sort_keys=True)
    key = cryptography.generate_key(algorithm="AES-256")
    encrypted = cryptography.encrypt(raw, key)
    checksum = hashlib.sha256(encrypted.encode()).hexdigest()
    logger.info("Payload encrypted, size=%d checksum=%s", len(encrypted), checksum[:8])
    return EncryptedPayload(
        ciphertext=encrypted,
        algorithm="AES-256",
        key_id=key.id,
        checksum=checksum,
    )


def decrypt_payload(payload: EncryptedPayload, key_store: dict) -> dict:
    key = key_store.get(payload.key_id)
    if not key:
        raise KeyError(f"Key not found: {payload.key_id}")
    raw = cryptography.decrypt(payload.ciphertext, key)
    checksum = hashlib.sha256(payload.ciphertext.encode()).hexdigest()
    if checksum != payload.checksum:
        raise ValueError("Checksum mismatch — payload may be tampered")
    logger.info("Payload decrypted successfully")
    return json.loads(raw)


def rotate_key(old_payload: EncryptedPayload, key_store: dict) -> EncryptedPayload:
    data = decrypt_payload(old_payload, key_store)
    new_payload = encrypt_payload(data)
    logger.info("Key rotated: %s → %s", old_payload.key_id, new_payload.key_id)
    return new_payload


def batch_encrypt(records: list[dict]) -> list[EncryptedPayload]:
    results = []
    for i, record in enumerate(records):
        try:
            results.append(encrypt_payload(record))
        except Exception as e:
            logger.error("Failed to encrypt record %d: %s", i, e)
    return results


def verify_checksum(payload: EncryptedPayload) -> bool:
    expected = hashlib.sha256(payload.ciphertext.encode()).hexdigest()
    return expected == payload.checksum


# ---------------------------------------------------------------------------
# Feature engineering
# ---------------------------------------------------------------------------

def normalize_features(matrix: list) -> np.ndarray:
    arr = np.array(matrix, dtype=float)
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0) + 1e-8
    logger.debug("Normalizing matrix shape=%s mean=%s", arr.shape, mean[:3])
    return (arr - mean) / std


def standardize(arr: np.ndarray) -> np.ndarray:
    min_val = np.min(arr, axis=0)
    max_val = np.max(arr, axis=0)
    denom = (max_val - min_val) + 1e-8
    return (arr - min_val) / denom


def one_hot_encode(labels: list[str], vocab: list[str]) -> np.ndarray:
    idx_map = {v: i for i, v in enumerate(vocab)}
    result = np.zeros((len(labels), len(vocab)), dtype=int)
    for row, label in enumerate(labels):
        if label in idx_map:
            result[row, idx_map[label]] = 1
    return result


def compute_pca(matrix: np.ndarray, n_components: int = 2) -> np.ndarray:
    centered = matrix - np.mean(matrix, axis=0)
    cov = np.cov(centered.T)
    eigenvalues, eigenvectors = np.linalg.eig(cov)
    idx = np.argsort(eigenvalues)[::-1]
    components = eigenvectors[:, idx[:n_components]]
    return centered @ components


def rolling_mean(arr: np.ndarray, window: int) -> np.ndarray:
    result = np.full_like(arr, np.nan)
    for i in range(window - 1, len(arr)):
        result[i] = np.mean(arr[i - window + 1 : i + 1])
    return result


def z_score_filter(arr: np.ndarray, threshold: float = 3.0) -> np.ndarray:
    mean = np.mean(arr)
    std = np.std(arr) + 1e-8
    z_scores = np.abs((arr - mean) / std)
    return arr[z_scores < threshold]


def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    dot = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return float(dot / (norm_a * norm_b))


def euclidean_distance(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.linalg.norm(a - b))


def build_feature_matrix(records: list[dict], keys: list[str]) -> FeatureMatrix:
    rows = []
    for record in records:
        row = [float(record.get(k, 0.0)) for k in keys]
        rows.append(row)
    data = np.array(rows, dtype=float)
    return FeatureMatrix(data=data, feature_names=keys)


# ---------------------------------------------------------------------------
# Data validation
# ---------------------------------------------------------------------------

def validate_schema(record: dict, schema: dict) -> ValidationResult:
    result = ValidationResult(is_valid=True)
    for field_name, field_spec in schema.items():
        if field_spec.get("required") and field_name not in record:
            result.add_error(f"Missing required field: {field_name}")
            continue
        if field_name in record:
            value = record[field_name]
            expected_type = field_spec.get("type")
            if expected_type and not isinstance(value, expected_type):
                result.add_error(f"Field {field_name}: expected {expected_type.__name__}, got {type(value).__name__}")
            min_val = field_spec.get("min")
            max_val = field_spec.get("max")
            if min_val is not None and value < min_val:
                result.add_error(f"Field {field_name}: {value} < min {min_val}")
            if max_val is not None and value > max_val:
                result.add_error(f"Field {field_name}: {value} > max {max_val}")
            pattern = field_spec.get("pattern")
            if pattern and isinstance(value, str):
                if not re.match(pattern, value):
                    result.add_error(f"Field {field_name}: does not match pattern {pattern}")
    result.score = 1.0 - (len(result.errors) / max(len(schema), 1))
    return result


def validate_batch(records: list[dict], schema: dict) -> list[ValidationResult]:
    return [validate_schema(r, schema) for r in records]


def deduplicate(records: list[dict], key: str) -> list[dict]:
    seen = set()
    result = []
    for r in records:
        val = r.get(key)
        if val not in seen:
            seen.add(val)
            result.append(r)
    return result


def flatten(nested: dict, prefix: str = "", sep: str = ".") -> dict:
    result = {}
    for k, v in nested.items():
        full_key = f"{prefix}{sep}{k}" if prefix else k
        if isinstance(v, dict):
            result.update(flatten(v, full_key, sep))
        else:
            result[full_key] = v
    return result


def chunk_list(lst: list, size: int) -> list[list]:
    return [lst[i : i + size] for i in range(0, len(lst), size)]


def merge_dicts(*dicts: dict) -> dict:
    result = {}
    for d in dicts:
        result.update(d)
    return result


# ---------------------------------------------------------------------------
# File I/O utilities
# ---------------------------------------------------------------------------

def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    logger.debug("Loaded JSON from %s (%d keys)", path, len(data) if isinstance(data, dict) else len(data))
    return data


def save_json(data: Any, path: str, indent: int = 2) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=indent, ensure_ascii=False)
    logger.info("Saved JSON to %s", path)


def load_jsonl(path: str) -> list[dict]:
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    logger.debug("Loaded %d records from %s", len(records), path)
    return records


def save_jsonl(records: list[dict], path: str) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")
    logger.info("Saved %d records to %s", len(records), path)


def read_chunks(path: str, chunk_size: int = CHUNK_SIZE) -> list[bytes]:
    chunks = []
    with open(path, "rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            chunks.append(chunk)
    return chunks


def file_checksum(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK_SIZE), b""):
            h.update(chunk)
    return h.hexdigest()


def safe_mkdir(path: str) -> Path:
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p


# ---------------------------------------------------------------------------
# String utilities
# ---------------------------------------------------------------------------

def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text.strip("-")


def truncate(text: str, max_len: int = 100, suffix: str = "...") -> str:
    if len(text) <= max_len:
        return text
    return text[: max_len - len(suffix)] + suffix


def camel_to_snake(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def snake_to_camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def mask_sensitive(text: str, visible: int = 4) -> str:
    if len(text) <= visible:
        return "*" * len(text)
    return text[:visible] + "*" * (len(text) - visible)


def extract_emails(text: str) -> list[str]:
    pattern = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
    return re.findall(pattern, text)


def extract_urls(text: str) -> list[str]:
    pattern = r"https?://[^\s]+"
    return re.findall(pattern, text)


def count_words(text: str) -> int:
    return len(text.split())


def remove_duplicates(lst: list) -> list:
    seen = set()
    result = []
    for item in lst:
        key = str(item)
        if key not in seen:
            seen.add(key)
            result.append(item)
    return result


# ---------------------------------------------------------------------------
# Math / statistics utilities
# ---------------------------------------------------------------------------

def safe_divide(a: float, b: float, default: float = 0.0) -> float:
    return a / b if b != 0 else default


def clamp(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-x))


def softmax(arr: np.ndarray) -> np.ndarray:
    shifted = arr - np.max(arr)
    exp = np.exp(shifted)
    return exp / np.sum(exp)


def entropy(probs: np.ndarray) -> float:
    probs = probs[probs > 0]
    return float(-np.sum(probs * np.log2(probs)))


def gini_impurity(labels: list) -> float:
    total = len(labels)
    if total == 0:
        return 0.0
    counts: dict = {}
    for l in labels:
        counts[l] = counts.get(l, 0) + 1
    return 1.0 - sum((c / total) ** 2 for c in counts.values())


def percentile(arr: np.ndarray, p: float) -> float:
    return float(np.percentile(arr, p))


def moving_average(values: list[float], window: int) -> list[float]:
    result = []
    for i in range(len(values)):
        start = max(0, i - window + 1)
        result.append(sum(values[start : i + 1]) / (i - start + 1))
    return result


def weighted_average(values: list[float], weights: list[float]) -> float:
    total_weight = sum(weights)
    if total_weight == 0:
        return 0.0
    return sum(v * w for v, w in zip(values, weights)) / total_weight


def normalize_scores(scores: list[float]) -> list[float]:
    if not scores:
        return []
    min_s = min(scores)
    max_s = max(scores)
    span = max_s - min_s
    if span == 0:
        return [0.5] * len(scores)
    return [(s - min_s) / span for s in scores]


# ---------------------------------------------------------------------------
# Hashing and fingerprinting
# ---------------------------------------------------------------------------

def sha256_hex(data: str) -> str:
    return hashlib.sha256(data.encode("utf-8")).hexdigest()


def md5_hex(data: str) -> str:
    return hashlib.md5(data.encode("utf-8")).hexdigest()


def fingerprint(record: dict) -> str:
    canonical = json.dumps(record, sort_keys=True, separators=(",", ":"))
    return sha256_hex(canonical)


def build_lookup(records: list[dict], key: str) -> dict:
    return {r[key]: r for r in records if key in r}


def group_by(records: list[dict], key: str) -> dict:
    groups: dict = {}
    for r in records:
        val = r.get(key)
        if val not in groups:
            groups[val] = []
        groups[val].append(r)
    return groups


# ---------------------------------------------------------------------------
# Environment / config helpers
# ---------------------------------------------------------------------------

def get_env(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


def require_env(key: str) -> str:
    val = os.environ.get(key)
    if val is None:
        raise EnvironmentError(f"Required environment variable not set: {key}")
    return val


def env_bool(key: str, default: bool = False) -> bool:
    val = os.environ.get(key, "").lower()
    if val in ("1", "true", "yes"):
        return True
    if val in ("0", "false", "no"):
        return False
    return default


def env_int(key: str, default: int = 0) -> int:
    try:
        return int(os.environ.get(key, default))
    except (ValueError, TypeError):
        return default


# ---------------------------------------------------------------------------
# Retry / resilience
# ---------------------------------------------------------------------------

def retry(fn, retries: int = MAX_RETRIES, exceptions: tuple = (Exception,)):
    last_exc = None
    for attempt in range(retries):
        try:
            return fn()
        except exceptions as e:
            last_exc = e
            logger.warning("Attempt %d/%d failed: %s", attempt + 1, retries, e)
    raise last_exc


def with_default(fn, default: Any = None) -> Any:
    try:
        return fn()
    except Exception as e:
        logger.debug("Returning default due to: %s", e)
        return default


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------

def log_dict(d: dict, label: str = "data") -> None:
    logger.debug("%s: %s", label, json.dumps(d, default=str, indent=2))


def log_timing(label: str, elapsed_ms: float) -> None:
    logger.info("%s completed in %.1f ms", label, elapsed_ms)


def log_batch_result(total: int, succeeded: int, failed: int) -> None:
    logger.info(
        "Batch complete: %d total, %d succeeded, %d failed (%.1f%% success)",
        total, succeeded, failed,
        100.0 * succeeded / total if total else 0,
    )


# ---------------------------------------------------------------------------
# Type coercion
# ---------------------------------------------------------------------------

def to_float(val: Any, default: float = 0.0) -> float:
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


def to_int(val: Any, default: int = 0) -> int:
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def to_bool(val: Any) -> bool:
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        return val.lower() in ("1", "true", "yes", "on")
    return bool(val)


def to_list(val: Any) -> list:
    if val is None:
        return []
    if isinstance(val, list):
        return val
    if isinstance(val, (tuple, set)):
        return list(val)
    return [val]


def ensure_dict(val: Any) -> dict:
    if isinstance(val, dict):
        return val
    if isinstance(val, str):
        try:
            return json.loads(val)
        except json.JSONDecodeError:
            return {}
    return {}


# ---------------------------------------------------------------------------
# Timestamp utilities
# ---------------------------------------------------------------------------

def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_iso(ts: str) -> datetime:
    return datetime.fromisoformat(ts.replace("Z", "+00:00"))


def days_since(ts: str) -> int:
    dt = parse_iso(ts)
    now = datetime.now(timezone.utc)
    return (now - dt).days


def is_expired(ts: str, ttl_days: int) -> bool:
    return days_since(ts) > ttl_days


def format_duration(ms: float) -> str:
    if ms < 1000:
        return f"{ms:.0f}ms"
    if ms < 60000:
        return f"{ms / 1000:.1f}s"
    return f"{ms / 60000:.1f}m"


# ---------------------------------------------------------------------------
# Aggregation helpers
# ---------------------------------------------------------------------------

def top_n(records: list[dict], key: str, n: int = 10) -> list[dict]:
    return sorted(records, key=lambda r: r.get(key, 0), reverse=True)[:n]


def bottom_n(records: list[dict], key: str, n: int = 10) -> list[dict]:
    return sorted(records, key=lambda r: r.get(key, 0))[:n]


def sum_field(records: list[dict], key: str) -> float:
    return sum(to_float(r.get(key, 0)) for r in records)


def avg_field(records: list[dict], key: str) -> float:
    vals = [to_float(r.get(key, 0)) for r in records]
    return sum(vals) / len(vals) if vals else 0.0


def count_by(records: list[dict], key: str) -> dict:
    counts: dict = {}
    for r in records:
        val = str(r.get(key, "unknown"))
        counts[val] = counts.get(val, 0) + 1
    return counts


def pivot(records: list[dict], row_key: str, col_key: str, val_key: str) -> dict:
    result: dict = {}
    for r in records:
        row = r.get(row_key)
        col = r.get(col_key)
        val = r.get(val_key)
        if row not in result:
            result[row] = {}
        result[row][col] = val
    return result
