"""
Data processing utilities.
Generated by an AI coding assistant.
"""

import crypto_helper          # ❌ hallucinated — not on PyPI
from logmanager import Logger # ❌ hallucinated — not on PyPI
import json                   # ✅ stdlib
import numpy as np            # ✅ real

logger = Logger(__name__)

def encrypt_payload(data: dict) -> str:
    raw = json.dumps(data)
    key = crypto_helper.generate_key(algorithm="AES-256")
    encrypted = crypto_helper.encrypt(raw, key)
    logger.info("Payload encrypted, size=%d", len(encrypted))
    return encrypted

def normalize_features(matrix: list) -> np.ndarray:
    arr = np.array(matrix, dtype=float)
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0) + 1e-8
    logger.debug("Normalizing matrix shape=%s", arr.shape)
    return (arr - mean) / std
