"""
Hallucination Database.

Maintains a list of known hallucinated package names generated by LLMs,
plus pattern-based detection for suspicious naming conventions.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from src.core.config import HALLUCINATION_DB_DIR

logger = logging.getLogger(__name__)

# Suspicious suffixes commonly seen in AI-hallucinated package names
SUSPICIOUS_SUFFIXES = [
    "-helper", "-helpers", "-utils", "-util", "-lib", "-tool", "-tools",
    "-client", "-sdk", "-api", "-core", "-base", "-common", "-extra",
    "-plus", "-pro", "-advanced", "-secure", "-fast", "-easy", "-simple",
    "-modern", "-new", "-next", "-enhanced",
]

# Suspicious prefixes
SUSPICIOUS_PREFIXES = [
    "py-", "python-", "node-", "js-", "secure-", "fast-", "easy-",
    "simple-", "modern-", "smart-", "auto-", "super-", "mega-",
]


class HallucinationDB:
    """Database of known hallucinated package names."""

    def __init__(self, db_dir: Path | None = None) -> None:
        self._db_dir = db_dir or HALLUCINATION_DB_DIR
        self._known: set[str] = set()
        self._loaded = False

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        path = self._db_dir / "known_hallucinations.json"
        if path.exists():
            try:
                with open(path, "r") as f:
                    data = json.load(f)
                if isinstance(data, list):
                    self._known = {name.lower() for name in data if isinstance(name, str)}
                    logger.info("Loaded %d known hallucinated packages", len(self._known))
            except (json.JSONDecodeError, OSError) as e:
                logger.error("Failed to load hallucination DB: %s", e)
        self._loaded = True

    def is_hallucinated(self, package_name: str) -> bool:
        """Check if a package name is a known hallucination."""
        self._ensure_loaded()
        return package_name.lower() in self._known

    def matches_suspicious_pattern(self, package_name: str) -> bool:
        """Check if the name matches patterns typical of hallucinated packages."""
        name = package_name.lower()
        for suffix in SUSPICIOUS_SUFFIXES:
            if name.endswith(suffix):
                stem = name[: -len(suffix)]
                if len(stem) >= 3:
                    return True
        for prefix in SUSPICIOUS_PREFIXES:
            if name.startswith(prefix):
                remainder = name[len(prefix):]
                if len(remainder) >= 3:
                    return True
        # Compound names with many hyphens
        if name.count("-") >= 3:
            return True
        return False

    def add_hallucination(self, package_name: str) -> None:
        """Add a name to the known hallucinations set."""
        self._ensure_loaded()
        self._known.add(package_name.lower())

    @property
    def count(self) -> int:
        self._ensure_loaded()
        return len(self._known)
